export const TipoUpload = {
    SHAPEFILE: 'SHAPEFILE',
    ICONE_TAG: 'ICONE_TAG',
    DOCUMENTO: 'DOCUMENTO',
    LOGO_PDM: 'LOGO_PDM',
    IMPORTACAO_ORCAMENTO: 'IMPORTACAO_ORCAMENTO',
    FOTO_PARLAMENTAR: 'FOTO_PARLAMENTAR',
    IMPORTACAO_PARLAMENTAR: 'IMPORTACAO_PARLAMENTAR',
    ATUALIZACAO_EM_LOTE_RELATORIO: 'ATUALIZACAO_EM_LOTE_RELATORIO',
} as const;
export type TipoUpload = (typeof TipoUpload)[keyof typeof TipoUpload];
