begin;

update regiao set pdm_codigo_sufixo = 'ARA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Agua Rasa', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'API' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Alto De Pinheiros', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'ANH' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Anhanguera', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'ARI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Aricanduva', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'AAL' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Artur Alvim', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BFU' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Barra Funda', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BVI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Bela Vista', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BEL' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Belem', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BRE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Bom Retiro', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BRS' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Bras', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BRL' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Brasilandia', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'BUT' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Butanta', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CAC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cachoeirinha', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CMB' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cambuci', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CBE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Campo Belo', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CGR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Campo Grande', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CLM' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Campo Limpo', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CNG' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cangaiba', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CRE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Capao Redondo', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CAR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Carrao', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CVE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Casa Verde', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CAD' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cidade Ademar', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CDU' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cidade Dutra', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CLD' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cidade Lider', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CTI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cidade Tiradentes', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CON' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Consolacao', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'CUR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Cursino', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'ERM' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Ermelino Matarazzo', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'FRE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Freguesia Do O', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'GRA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Grajau', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'GUA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Guaianases', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'IGU' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Iguatemi', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'IPI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Ipiranga', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'IBI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Itaim Bibi', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'IPA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Itaim Paulista', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'ITQ' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Itaquera', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JAB' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jabaquara', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JAC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jacana', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JAG' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jaguara', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JRE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jaguare', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JAR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jaragua', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JDA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jardim Angela', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JDH' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jardim Helena', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JDP' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jardim Paulista', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JDS' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jardim Sao Luis', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'JBO' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Jose Bonifacio', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'LAJ' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Lajeado', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'LAP' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Lapa', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'LIB' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Liberdade', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'LIM' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Limao', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'MAN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Mandaqui', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'MAR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Marsilac', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'MOE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Moema', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'MOO' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Mooca', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'MOR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Morumbi', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PLH' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Parelheiros', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PRI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Pari', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PQC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Parque Do Carmo', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PDR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Pedreira', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PEN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Penha', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PRD' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Perdizes', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PRS' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Perus', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PIN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Pinheiros', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PIR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Pirituba', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'PRA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Ponte Rasa', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'RTA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Raposo Tavares', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'REP' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Republica', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'RPE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Rio Pequeno', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SAC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sacoma', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SCE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Santa Cecilia', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'STN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Santana', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SAM' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Santo Amaro', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SDO' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sao Domingos', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SLU' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sao Lucas', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SMT' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sao Mateus', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SMI' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sao Miguel', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SRA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sao Rafael', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SAP' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Sapopemba', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SAU' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Saude', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SEE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Se', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'SOC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Socorro', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'TAT' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Tatuape', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'TRE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Tremembe', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'TUC' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Tucuruvi', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VAN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Andrade', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VCR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Curuca', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VFO' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Formosa', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VGL' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Guilherme', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VJA' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Jacui', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VLE' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Leopoldina', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VMR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Maria', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VMN' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Mariana', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VMT' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Matilde', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VMD' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Medeiros', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VPR' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Prudente', '[^a-zA-Z]', '', 'g');
update regiao set pdm_codigo_sufixo = 'VSO' where nivel=4 and regexp_replace(descricao,  '[^a-zA-Z]', '', 'g') =regexp_replace( 'Vila Sonia', '[^a-zA-Z]', '', 'g');

commit;
