-- AlterTable
ALTER TABLE "wiki_link" ALTER COLUMN "criado_em" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "atualizado_em" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "atualizado_em" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "removido_em" SET DATA TYPE TIMESTAMPTZ(6);
