export const CONST_BOT_USER_ID = -1;
export const CONST_CRONO_VAR_CATEGORICA_ID = -1;
export const CONST_TIPO_NOTA_DIST_RECURSO = -1;
export const CONST_TIPO_NOTA_TRANSF_GOV = -2;
export const CONST_VAR_SEM_UN_MEDIDA = -1;
export const CONST_COD_NOTA_DIST_RECURSO = 'Aviso de distribuição de recurso';
export const CONST_COD_NOTA_TRANSF_GOV = 'Transfere Gov';
export const CONST_PERFIL_PARTICIPANTE_EQUIPE = 'Participante em equipes';
export const CONST_PERFIL_PARTICIPANTE_EQUIPE_PDM = 'Participante em equipes<PDM>';
