from .geosampa_client import GeoSampa

from config import GEOSAMPA_WFS_DOMAIN, GEOSAMPA_API_VERSION, DISTANCIA_PADRAO_MTS_GEOSAMPA

geosampa = GeoSampa(GEOSAMPA_WFS_DOMAIN, GEOSAMPA_API_VERSION, DISTANCIA_PADRAO_MTS_GEOSAMPA)