insert into regiao (descricao, codigo, nivel) values ('Adamantina', '3500105', 1);
insert into regiao (descricao, codigo, nivel) values ('Adolfo', '3500204', 1);
insert into regiao (descricao, codigo, nivel) values ('Aguaí', '3500303', 1);
insert into regiao (descricao, codigo, nivel) values ('Águas da Prata', '3500402', 1);
insert into regiao (descricao, codigo, nivel) values ('Águas de Lindóia', '3500501', 1);
insert into regiao (descricao, codigo, nivel) values ('Águas de Santa Bárbara', '3500550', 1);
insert into regiao (descricao, codigo, nivel) values ('Águas de São Pedro', '3500600', 1);
insert into regiao (descricao, codigo, nivel) values ('Agudos', '3500709', 1);
insert into regiao (descricao, codigo, nivel) values ('Alambari', '3500758', 1);
insert into regiao (descricao, codigo, nivel) values ('Alfredo Marcondes', '3500808', 1);
insert into regiao (descricao, codigo, nivel) values ('Altair', '3500907', 1);
insert into regiao (descricao, codigo, nivel) values ('Altinópolis', '3501004', 1);
insert into regiao (descricao, codigo, nivel) values ('Alto Alegre', '3501103', 1);
insert into regiao (descricao, codigo, nivel) values ('Alumínio', '3501152', 1);
insert into regiao (descricao, codigo, nivel) values ('Álvares Florence', '3501202', 1);
insert into regiao (descricao, codigo, nivel) values ('Álvares Machado', '3501301', 1);
insert into regiao (descricao, codigo, nivel) values ('Álvaro de Carvalho', '3501400', 1);
insert into regiao (descricao, codigo, nivel) values ('Alvinlândia', '3501509', 1);
insert into regiao (descricao, codigo, nivel) values ('Americana', '3501608', 1);
insert into regiao (descricao, codigo, nivel) values ('Américo Brasiliense', '3501707', 1);
insert into regiao (descricao, codigo, nivel) values ('Américo de Campos', '3501806', 1);
insert into regiao (descricao, codigo, nivel) values ('Amparo', '3501905', 1);
insert into regiao (descricao, codigo, nivel) values ('Analândia', '3502002', 1);
insert into regiao (descricao, codigo, nivel) values ('Andradina', '3502101', 1);
insert into regiao (descricao, codigo, nivel) values ('Angatuba', '3502200', 1);
insert into regiao (descricao, codigo, nivel) values ('Anhembi', '3502309', 1);
insert into regiao (descricao, codigo, nivel) values ('Anhumas', '3502408', 1);
insert into regiao (descricao, codigo, nivel) values ('Aparecida', '3502507', 1);
insert into regiao (descricao, codigo, nivel) values (E'Aparecida d''Oeste', '3502606', 1);
insert into regiao (descricao, codigo, nivel) values ('Apiaí', '3502705', 1);
insert into regiao (descricao, codigo, nivel) values ('Araçariguama', '3502754', 1);
insert into regiao (descricao, codigo, nivel) values ('Araçatuba', '3502804', 1);
insert into regiao (descricao, codigo, nivel) values ('Araçoiaba da Serra', '3502903', 1);
insert into regiao (descricao, codigo, nivel) values ('Aramina', '3503000', 1);
insert into regiao (descricao, codigo, nivel) values ('Arandu', '3503109', 1);
insert into regiao (descricao, codigo, nivel) values ('Arapeí', '3503158', 1);
insert into regiao (descricao, codigo, nivel) values ('Araraquara', '3503208', 1);
insert into regiao (descricao, codigo, nivel) values ('Araras', '3503307', 1);
insert into regiao (descricao, codigo, nivel) values ('Arco-Íris', '3503356', 1);
insert into regiao (descricao, codigo, nivel) values ('Arealva', '3503406', 1);
insert into regiao (descricao, codigo, nivel) values ('Areias', '3503505', 1);
insert into regiao (descricao, codigo, nivel) values ('Areiópolis', '3503604', 1);
insert into regiao (descricao, codigo, nivel) values ('Ariranha', '3503703', 1);
insert into regiao (descricao, codigo, nivel) values ('Artur Nogueira', '3503802', 1);
insert into regiao (descricao, codigo, nivel) values ('Arujá', '3503901', 1);
insert into regiao (descricao, codigo, nivel) values ('Aspásia', '3503950', 1);
insert into regiao (descricao, codigo, nivel) values ('Assis', '3504008', 1);
insert into regiao (descricao, codigo, nivel) values ('Atibaia', '3504107', 1);
insert into regiao (descricao, codigo, nivel) values ('Auriflama', '3504206', 1);
insert into regiao (descricao, codigo, nivel) values ('Avaí', '3504305', 1);
insert into regiao (descricao, codigo, nivel) values ('Avanhandava', '3504404', 1);
insert into regiao (descricao, codigo, nivel) values ('Avaré', '3504503', 1);
insert into regiao (descricao, codigo, nivel) values ('Bady Bassitt', '3504602', 1);
insert into regiao (descricao, codigo, nivel) values ('Balbinos', '3504701', 1);
insert into regiao (descricao, codigo, nivel) values ('Bálsamo', '3504800', 1);
insert into regiao (descricao, codigo, nivel) values ('Bananal', '3504909', 1);
insert into regiao (descricao, codigo, nivel) values ('Barão de Antonina', '3505005', 1);
insert into regiao (descricao, codigo, nivel) values ('Barbosa', '3505104', 1);
insert into regiao (descricao, codigo, nivel) values ('Bariri', '3505203', 1);
insert into regiao (descricao, codigo, nivel) values ('Barra Bonita', '3505302', 1);
insert into regiao (descricao, codigo, nivel) values ('Barra do Chapéu', '3505351', 1);
insert into regiao (descricao, codigo, nivel) values ('Barra do Turvo', '3505401', 1);
insert into regiao (descricao, codigo, nivel) values ('Barretos', '3505500', 1);
insert into regiao (descricao, codigo, nivel) values ('Barrinha', '3505609', 1);
insert into regiao (descricao, codigo, nivel) values ('Barueri', '3505708', 1);
insert into regiao (descricao, codigo, nivel) values ('Bastos', '3505807', 1);
insert into regiao (descricao, codigo, nivel) values ('Batatais', '3505906', 1);
insert into regiao (descricao, codigo, nivel) values ('Bauru', '3506003', 1);
insert into regiao (descricao, codigo, nivel) values ('Bebedouro', '3506102', 1);
insert into regiao (descricao, codigo, nivel) values ('Bento de Abreu', '3506201', 1);
insert into regiao (descricao, codigo, nivel) values ('Bernardino de Campos', '3506300', 1);
insert into regiao (descricao, codigo, nivel) values ('Bertioga', '3506359', 1);
insert into regiao (descricao, codigo, nivel) values ('Bilac', '3506409', 1);
insert into regiao (descricao, codigo, nivel) values ('Birigui', '3506508', 1);
insert into regiao (descricao, codigo, nivel) values ('Biritiba Mirim', '3506607', 1);
insert into regiao (descricao, codigo, nivel) values ('Boa Esperança do Sul', '3506706', 1);
insert into regiao (descricao, codigo, nivel) values ('Bocaina', '3506805', 1);
insert into regiao (descricao, codigo, nivel) values ('Bofete', '3506904', 1);
insert into regiao (descricao, codigo, nivel) values ('Boituva', '3507001', 1);
insert into regiao (descricao, codigo, nivel) values ('Bom Jesus dos Perdões', '3507100', 1);
insert into regiao (descricao, codigo, nivel) values ('Bom Sucesso de Itararé', '3507159', 1);
insert into regiao (descricao, codigo, nivel) values ('Borá', '3507209', 1);
insert into regiao (descricao, codigo, nivel) values ('Boraceia', '3507308', 1);
insert into regiao (descricao, codigo, nivel) values ('Borborema', '3507407', 1);
insert into regiao (descricao, codigo, nivel) values ('Borebi', '3507456', 1);
insert into regiao (descricao, codigo, nivel) values ('Botucatu', '3507506', 1);
insert into regiao (descricao, codigo, nivel) values ('Bragança Paulista', '3507605', 1);
insert into regiao (descricao, codigo, nivel) values ('Braúna', '3507704', 1);
insert into regiao (descricao, codigo, nivel) values ('Brejo Alegre', '3507753', 1);
insert into regiao (descricao, codigo, nivel) values ('Brodowski', '3507803', 1);
insert into regiao (descricao, codigo, nivel) values ('Brotas', '3507902', 1);
insert into regiao (descricao, codigo, nivel) values ('Buri', '3508009', 1);
insert into regiao (descricao, codigo, nivel) values ('Buritama', '3508108', 1);
insert into regiao (descricao, codigo, nivel) values ('Buritizal', '3508207', 1);
insert into regiao (descricao, codigo, nivel) values ('Cabrália Paulista', '3508306', 1);
insert into regiao (descricao, codigo, nivel) values ('Cabreúva', '3508405', 1);
insert into regiao (descricao, codigo, nivel) values ('Caçapava', '3508504', 1);
insert into regiao (descricao, codigo, nivel) values ('Cachoeira Paulista', '3508603', 1);
insert into regiao (descricao, codigo, nivel) values ('Caconde', '3508702', 1);
insert into regiao (descricao, codigo, nivel) values ('Cafelândia', '3508801', 1);
insert into regiao (descricao, codigo, nivel) values ('Caiabu', '3508900', 1);
insert into regiao (descricao, codigo, nivel) values ('Caieiras', '3509007', 1);
insert into regiao (descricao, codigo, nivel) values ('Caiuá', '3509106', 1);
insert into regiao (descricao, codigo, nivel) values ('Cajamar', '3509205', 1);
insert into regiao (descricao, codigo, nivel) values ('Cajati', '3509254', 1);
insert into regiao (descricao, codigo, nivel) values ('Cajobi', '3509304', 1);
insert into regiao (descricao, codigo, nivel) values ('Cajuru', '3509403', 1);
insert into regiao (descricao, codigo, nivel) values ('Campina do Monte Alegre', '3509452', 1);
insert into regiao (descricao, codigo, nivel) values ('Campinas', '3509502', 1);
insert into regiao (descricao, codigo, nivel) values ('Campo Limpo Paulista', '3509601', 1);
insert into regiao (descricao, codigo, nivel) values ('Campos do Jordão', '3509700', 1);
insert into regiao (descricao, codigo, nivel) values ('Campos Novos Paulista', '3509809', 1);
insert into regiao (descricao, codigo, nivel) values ('Cananéia', '3509908', 1);
insert into regiao (descricao, codigo, nivel) values ('Canas', '3509957', 1);
insert into regiao (descricao, codigo, nivel) values ('Cândido Mota', '3510005', 1);
insert into regiao (descricao, codigo, nivel) values ('Cândido Rodrigues', '3510104', 1);
insert into regiao (descricao, codigo, nivel) values ('Canitar', '3510153', 1);
insert into regiao (descricao, codigo, nivel) values ('Capão Bonito', '3510203', 1);
insert into regiao (descricao, codigo, nivel) values ('Capela do Alto', '3510302', 1);
insert into regiao (descricao, codigo, nivel) values ('Capivari', '3510401', 1);
insert into regiao (descricao, codigo, nivel) values ('Caraguatatuba', '3510500', 1);
insert into regiao (descricao, codigo, nivel) values ('Carapicuíba', '3510609', 1);
insert into regiao (descricao, codigo, nivel) values ('Cardoso', '3510708', 1);
insert into regiao (descricao, codigo, nivel) values ('Casa Branca', '3510807', 1);
insert into regiao (descricao, codigo, nivel) values ('Cássia dos Coqueiros', '3510906', 1);
insert into regiao (descricao, codigo, nivel) values ('Castilho', '3511003', 1);
insert into regiao (descricao, codigo, nivel) values ('Catanduva', '3511102', 1);
insert into regiao (descricao, codigo, nivel) values ('Catiguá', '3511201', 1);
insert into regiao (descricao, codigo, nivel) values ('Cedral', '3511300', 1);
insert into regiao (descricao, codigo, nivel) values ('Cerqueira César', '3511409', 1);
insert into regiao (descricao, codigo, nivel) values ('Cerquilho', '3511508', 1);
insert into regiao (descricao, codigo, nivel) values ('Cesário Lange', '3511607', 1);
insert into regiao (descricao, codigo, nivel) values ('Charqueada', '3511706', 1);
insert into regiao (descricao, codigo, nivel) values ('Chavantes', '3557204', 1);
insert into regiao (descricao, codigo, nivel) values ('Clementina', '3511904', 1);
insert into regiao (descricao, codigo, nivel) values ('Colina', '3512001', 1);
insert into regiao (descricao, codigo, nivel) values ('Colômbia', '3512100', 1);
insert into regiao (descricao, codigo, nivel) values ('Conchal', '3512209', 1);
insert into regiao (descricao, codigo, nivel) values ('Conchas', '3512308', 1);
insert into regiao (descricao, codigo, nivel) values ('Cordeirópolis', '3512407', 1);
insert into regiao (descricao, codigo, nivel) values ('Coroados', '3512506', 1);
insert into regiao (descricao, codigo, nivel) values ('Coronel Macedo', '3512605', 1);
insert into regiao (descricao, codigo, nivel) values ('Corumbataí', '3512704', 1);
insert into regiao (descricao, codigo, nivel) values ('Cosmópolis', '3512803', 1);
insert into regiao (descricao, codigo, nivel) values ('Cosmorama', '3512902', 1);
insert into regiao (descricao, codigo, nivel) values ('Cotia', '3513009', 1);
insert into regiao (descricao, codigo, nivel) values ('Cravinhos', '3513108', 1);
insert into regiao (descricao, codigo, nivel) values ('Cristais Paulista', '3513207', 1);
insert into regiao (descricao, codigo, nivel) values ('Cruzália', '3513306', 1);
insert into regiao (descricao, codigo, nivel) values ('Cruzeiro', '3513405', 1);
insert into regiao (descricao, codigo, nivel) values ('Cubatão', '3513504', 1);
insert into regiao (descricao, codigo, nivel) values ('Cunha', '3513603', 1);
insert into regiao (descricao, codigo, nivel) values ('Descalvado', '3513702', 1);
insert into regiao (descricao, codigo, nivel) values ('Diadema', '3513801', 1);
insert into regiao (descricao, codigo, nivel) values ('Dirce Reis', '3513850', 1);
insert into regiao (descricao, codigo, nivel) values ('Divinolândia', '3513900', 1);
insert into regiao (descricao, codigo, nivel) values ('Dobrada', '3514007', 1);
insert into regiao (descricao, codigo, nivel) values ('Dois Córregos', '3514106', 1);
insert into regiao (descricao, codigo, nivel) values ('Dolcinópolis', '3514205', 1);
insert into regiao (descricao, codigo, nivel) values ('Dourado', '3514304', 1);
insert into regiao (descricao, codigo, nivel) values ('Dracena', '3514403', 1);
insert into regiao (descricao, codigo, nivel) values ('Duartina', '3514502', 1);
insert into regiao (descricao, codigo, nivel) values ('Dumont', '3514601', 1);
insert into regiao (descricao, codigo, nivel) values ('Echaporã', '3514700', 1);
insert into regiao (descricao, codigo, nivel) values ('Eldorado', '3514809', 1);
insert into regiao (descricao, codigo, nivel) values ('Elias Fausto', '3514908', 1);
insert into regiao (descricao, codigo, nivel) values ('Elisiário', '3514924', 1);
insert into regiao (descricao, codigo, nivel) values ('Embaúba', '3514957', 1);
insert into regiao (descricao, codigo, nivel) values ('Embu das Artes', '3515004', 1);
insert into regiao (descricao, codigo, nivel) values ('Embu-Guaçu', '3515103', 1);
insert into regiao (descricao, codigo, nivel) values ('Emilianópolis', '3515129', 1);
insert into regiao (descricao, codigo, nivel) values ('Engenheiro Coelho', '3515152', 1);
insert into regiao (descricao, codigo, nivel) values ('Espírito Santo do Pinhal', '3515186', 1);
insert into regiao (descricao, codigo, nivel) values ('Espírito Santo do Turvo', '3515194', 1);
insert into regiao (descricao, codigo, nivel) values ('Estiva Gerbi', '3557303', 1);
insert into regiao (descricao, codigo, nivel) values ('Estrela do Norte', '3515301', 1);
insert into regiao (descricao, codigo, nivel) values (E'Estrela d''Oeste', '3515202', 1);
insert into regiao (descricao, codigo, nivel) values ('Euclides da Cunha Paulista', '3515350', 1);
insert into regiao (descricao, codigo, nivel) values ('Fartura', '3515400', 1);
insert into regiao (descricao, codigo, nivel) values ('Fernando Prestes', '3515608', 1);
insert into regiao (descricao, codigo, nivel) values ('Fernandópolis', '3515509', 1);
insert into regiao (descricao, codigo, nivel) values ('Fernão', '3515657', 1);
insert into regiao (descricao, codigo, nivel) values ('Ferraz de Vasconcelos', '3515707', 1);
insert into regiao (descricao, codigo, nivel) values ('Flora Rica', '3515806', 1);
insert into regiao (descricao, codigo, nivel) values ('Floreal', '3515905', 1);
insert into regiao (descricao, codigo, nivel) values ('Flórida Paulista', '3516002', 1);
insert into regiao (descricao, codigo, nivel) values ('Florínea', '3516101', 1);
insert into regiao (descricao, codigo, nivel) values ('Franca', '3516200', 1);
insert into regiao (descricao, codigo, nivel) values ('Francisco Morato', '3516309', 1);
insert into regiao (descricao, codigo, nivel) values ('Franco da Rocha', '3516408', 1);
insert into regiao (descricao, codigo, nivel) values ('Gabriel Monteiro', '3516507', 1);
insert into regiao (descricao, codigo, nivel) values ('Gália', '3516606', 1);
insert into regiao (descricao, codigo, nivel) values ('Garça', '3516705', 1);
insert into regiao (descricao, codigo, nivel) values ('Gastão Vidigal', '3516804', 1);
insert into regiao (descricao, codigo, nivel) values ('Gavião Peixoto', '3516853', 1);
insert into regiao (descricao, codigo, nivel) values ('General Salgado', '3516903', 1);
insert into regiao (descricao, codigo, nivel) values ('Getulina', '3517000', 1);
insert into regiao (descricao, codigo, nivel) values ('Glicério', '3517109', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaiçara', '3517208', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaimbê', '3517307', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaíra', '3517406', 1);
insert into regiao (descricao, codigo, nivel) values ('Guapiaçu', '3517505', 1);
insert into regiao (descricao, codigo, nivel) values ('Guapiara', '3517604', 1);
insert into regiao (descricao, codigo, nivel) values ('Guará', '3517703', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaraçaí', '3517802', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaraci', '3517901', 1);
insert into regiao (descricao, codigo, nivel) values (E'Guarani d''Oeste', '3518008', 1);
insert into regiao (descricao, codigo, nivel) values ('Guarantã', '3518107', 1);
insert into regiao (descricao, codigo, nivel) values ('Guararapes', '3518206', 1);
insert into regiao (descricao, codigo, nivel) values ('Guararema', '3518305', 1);
insert into regiao (descricao, codigo, nivel) values ('Guaratinguetá', '3518404', 1);
insert into regiao (descricao, codigo, nivel) values ('Guareí', '3518503', 1);
insert into regiao (descricao, codigo, nivel) values ('Guariba', '3518602', 1);
insert into regiao (descricao, codigo, nivel) values ('Guarujá', '3518701', 1);
insert into regiao (descricao, codigo, nivel) values ('Guarulhos', '3518800', 1);
insert into regiao (descricao, codigo, nivel) values ('Guatapará', '3518859', 1);
insert into regiao (descricao, codigo, nivel) values ('Guzolândia', '3518909', 1);
insert into regiao (descricao, codigo, nivel) values ('Herculândia', '3519006', 1);
insert into regiao (descricao, codigo, nivel) values ('Holambra', '3519055', 1);
insert into regiao (descricao, codigo, nivel) values ('Hortolândia', '3519071', 1);
insert into regiao (descricao, codigo, nivel) values ('Iacanga', '3519105', 1);
insert into regiao (descricao, codigo, nivel) values ('Iacri', '3519204', 1);
insert into regiao (descricao, codigo, nivel) values ('Iaras', '3519253', 1);
insert into regiao (descricao, codigo, nivel) values ('Ibaté', '3519303', 1);
insert into regiao (descricao, codigo, nivel) values ('Ibirá', '3519402', 1);
insert into regiao (descricao, codigo, nivel) values ('Ibirarema', '3519501', 1);
insert into regiao (descricao, codigo, nivel) values ('Ibitinga', '3519600', 1);
insert into regiao (descricao, codigo, nivel) values ('Ibiúna', '3519709', 1);
insert into regiao (descricao, codigo, nivel) values ('Icém', '3519808', 1);
insert into regiao (descricao, codigo, nivel) values ('Iepê', '3519907', 1);
insert into regiao (descricao, codigo, nivel) values ('Igaraçu do Tietê', '3520004', 1);
insert into regiao (descricao, codigo, nivel) values ('Igarapava', '3520103', 1);
insert into regiao (descricao, codigo, nivel) values ('Igaratá', '3520202', 1);
insert into regiao (descricao, codigo, nivel) values ('Iguape', '3520301', 1);
insert into regiao (descricao, codigo, nivel) values ('Ilha Comprida', '3520426', 1);
insert into regiao (descricao, codigo, nivel) values ('Ilha Solteira', '3520442', 1);
insert into regiao (descricao, codigo, nivel) values ('Ilhabela', '3520400', 1);
insert into regiao (descricao, codigo, nivel) values ('Indaiatuba', '3520509', 1);
insert into regiao (descricao, codigo, nivel) values ('Indiana', '3520608', 1);
insert into regiao (descricao, codigo, nivel) values ('Indiaporã', '3520707', 1);
insert into regiao (descricao, codigo, nivel) values ('Inúbia Paulista', '3520806', 1);
insert into regiao (descricao, codigo, nivel) values ('Ipaussu', '3520905', 1);
insert into regiao (descricao, codigo, nivel) values ('Iperó', '3521002', 1);
insert into regiao (descricao, codigo, nivel) values ('Ipeúna', '3521101', 1);
insert into regiao (descricao, codigo, nivel) values ('Ipiguá', '3521150', 1);
insert into regiao (descricao, codigo, nivel) values ('Iporanga', '3521200', 1);
insert into regiao (descricao, codigo, nivel) values ('Ipuã', '3521309', 1);
insert into regiao (descricao, codigo, nivel) values ('Iracemápolis', '3521408', 1);
insert into regiao (descricao, codigo, nivel) values ('Irapuã', '3521507', 1);
insert into regiao (descricao, codigo, nivel) values ('Irapuru', '3521606', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaberá', '3521705', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaí', '3521804', 1);
insert into regiao (descricao, codigo, nivel) values ('Itajobi', '3521903', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaju', '3522000', 1);
insert into regiao (descricao, codigo, nivel) values ('Itanhaém', '3522109', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaoca', '3522158', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapecerica da Serra', '3522208', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapetininga', '3522307', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapeva', '3522406', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapevi', '3522505', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapira', '3522604', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapirapuã Paulista', '3522653', 1);
insert into regiao (descricao, codigo, nivel) values ('Itápolis', '3522703', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaporanga', '3522802', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapuí', '3522901', 1);
insert into regiao (descricao, codigo, nivel) values ('Itapura', '3523008', 1);
insert into regiao (descricao, codigo, nivel) values ('Itaquaquecetuba', '3523107', 1);
insert into regiao (descricao, codigo, nivel) values ('Itararé', '3523206', 1);
insert into regiao (descricao, codigo, nivel) values ('Itariri', '3523305', 1);
insert into regiao (descricao, codigo, nivel) values ('Itatiba', '3523404', 1);
insert into regiao (descricao, codigo, nivel) values ('Itatinga', '3523503', 1);
insert into regiao (descricao, codigo, nivel) values ('Itirapina', '3523602', 1);
insert into regiao (descricao, codigo, nivel) values ('Itirapuã', '3523701', 1);
insert into regiao (descricao, codigo, nivel) values ('Itobi', '3523800', 1);
insert into regiao (descricao, codigo, nivel) values ('Itu', '3523909', 1);
insert into regiao (descricao, codigo, nivel) values ('Itupeva', '3524006', 1);
insert into regiao (descricao, codigo, nivel) values ('Ituverava', '3524105', 1);
insert into regiao (descricao, codigo, nivel) values ('Jaborandi', '3524204', 1);
insert into regiao (descricao, codigo, nivel) values ('Jaboticabal', '3524303', 1);
insert into regiao (descricao, codigo, nivel) values ('Jacareí', '3524402', 1);
insert into regiao (descricao, codigo, nivel) values ('Jaci', '3524501', 1);
insert into regiao (descricao, codigo, nivel) values ('Jacupiranga', '3524600', 1);
insert into regiao (descricao, codigo, nivel) values ('Jaguariúna', '3524709', 1);
insert into regiao (descricao, codigo, nivel) values ('Jales', '3524808', 1);
insert into regiao (descricao, codigo, nivel) values ('Jambeiro', '3524907', 1);
insert into regiao (descricao, codigo, nivel) values ('Jandira', '3525003', 1);
insert into regiao (descricao, codigo, nivel) values ('Jardinópolis', '3525102', 1);
insert into regiao (descricao, codigo, nivel) values ('Jarinu', '3525201', 1);
insert into regiao (descricao, codigo, nivel) values ('Jaú', '3525300', 1);
insert into regiao (descricao, codigo, nivel) values ('Jeriquara', '3525409', 1);
insert into regiao (descricao, codigo, nivel) values ('Joanópolis', '3525508', 1);
insert into regiao (descricao, codigo, nivel) values ('João Ramalho', '3525607', 1);
insert into regiao (descricao, codigo, nivel) values ('José Bonifácio', '3525706', 1);
insert into regiao (descricao, codigo, nivel) values ('Júlio Mesquita', '3525805', 1);
insert into regiao (descricao, codigo, nivel) values ('Jumirim', '3525854', 1);
insert into regiao (descricao, codigo, nivel) values ('Jundiaí', '3525904', 1);
insert into regiao (descricao, codigo, nivel) values ('Junqueirópolis', '3526001', 1);
insert into regiao (descricao, codigo, nivel) values ('Juquiá', '3526100', 1);
insert into regiao (descricao, codigo, nivel) values ('Juquitiba', '3526209', 1);
insert into regiao (descricao, codigo, nivel) values ('Lagoinha', '3526308', 1);
insert into regiao (descricao, codigo, nivel) values ('Laranjal Paulista', '3526407', 1);
insert into regiao (descricao, codigo, nivel) values ('Lavínia', '3526506', 1);
insert into regiao (descricao, codigo, nivel) values ('Lavrinhas', '3526605', 1);
insert into regiao (descricao, codigo, nivel) values ('Leme', '3526704', 1);
insert into regiao (descricao, codigo, nivel) values ('Lençóis Paulista', '3526803', 1);
insert into regiao (descricao, codigo, nivel) values ('Limeira', '3526902', 1);
insert into regiao (descricao, codigo, nivel) values ('Lindoia', '3527009', 1);
insert into regiao (descricao, codigo, nivel) values ('Lins', '3527108', 1);
insert into regiao (descricao, codigo, nivel) values ('Lorena', '3527207', 1);
insert into regiao (descricao, codigo, nivel) values ('Lourdes', '3527256', 1);
insert into regiao (descricao, codigo, nivel) values ('Louveira', '3527306', 1);
insert into regiao (descricao, codigo, nivel) values ('Lucélia', '3527405', 1);
insert into regiao (descricao, codigo, nivel) values ('Lucianópolis', '3527504', 1);
insert into regiao (descricao, codigo, nivel) values ('Luiz Antônio', '3527603', 1);
insert into regiao (descricao, codigo, nivel) values ('Luiziânia', '3527702', 1);
insert into regiao (descricao, codigo, nivel) values ('Lupércio', '3527801', 1);
insert into regiao (descricao, codigo, nivel) values ('Lutécia', '3527900', 1);
insert into regiao (descricao, codigo, nivel) values ('Macatuba', '3528007', 1);
insert into regiao (descricao, codigo, nivel) values ('Macaubal', '3528106', 1);
insert into regiao (descricao, codigo, nivel) values ('Macedônia', '3528205', 1);
insert into regiao (descricao, codigo, nivel) values ('Magda', '3528304', 1);
insert into regiao (descricao, codigo, nivel) values ('Mairinque', '3528403', 1);
insert into regiao (descricao, codigo, nivel) values ('Mairiporã', '3528502', 1);
insert into regiao (descricao, codigo, nivel) values ('Manduri', '3528601', 1);
insert into regiao (descricao, codigo, nivel) values ('Marabá Paulista', '3528700', 1);
insert into regiao (descricao, codigo, nivel) values ('Maracaí', '3528809', 1);
insert into regiao (descricao, codigo, nivel) values ('Marapoama', '3528858', 1);
insert into regiao (descricao, codigo, nivel) values ('Mariápolis', '3528908', 1);
insert into regiao (descricao, codigo, nivel) values ('Marília', '3529005', 1);
insert into regiao (descricao, codigo, nivel) values ('Marinópolis', '3529104', 1);
insert into regiao (descricao, codigo, nivel) values ('Martinópolis', '3529203', 1);
insert into regiao (descricao, codigo, nivel) values ('Matão', '3529302', 1);
insert into regiao (descricao, codigo, nivel) values ('Mauá', '3529401', 1);
insert into regiao (descricao, codigo, nivel) values ('Mendonça', '3529500', 1);
insert into regiao (descricao, codigo, nivel) values ('Meridiano', '3529609', 1);
insert into regiao (descricao, codigo, nivel) values ('Mesópolis', '3529658', 1);
insert into regiao (descricao, codigo, nivel) values ('Miguelópolis', '3529708', 1);
insert into regiao (descricao, codigo, nivel) values ('Mineiros do Tietê', '3529807', 1);
insert into regiao (descricao, codigo, nivel) values ('Mira Estrela', '3530003', 1);
insert into regiao (descricao, codigo, nivel) values ('Miracatu', '3529906', 1);
insert into regiao (descricao, codigo, nivel) values ('Mirandópolis', '3530102', 1);
insert into regiao (descricao, codigo, nivel) values ('Mirante do Paranapanema', '3530201', 1);
insert into regiao (descricao, codigo, nivel) values ('Mirassol', '3530300', 1);
insert into regiao (descricao, codigo, nivel) values ('Mirassolândia', '3530409', 1);
insert into regiao (descricao, codigo, nivel) values ('Mococa', '3530508', 1);
insert into regiao (descricao, codigo, nivel) values ('Mogi das Cruzes', '3530607', 1);
insert into regiao (descricao, codigo, nivel) values ('Mogi Guaçu', '3530706', 1);
insert into regiao (descricao, codigo, nivel) values ('Mogi Mirim', '3530805', 1);
insert into regiao (descricao, codigo, nivel) values ('Mombuca', '3530904', 1);
insert into regiao (descricao, codigo, nivel) values ('Monções', '3531001', 1);
insert into regiao (descricao, codigo, nivel) values ('Mongaguá', '3531100', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Alegre do Sul', '3531209', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Alto', '3531308', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Aprazível', '3531407', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Azul Paulista', '3531506', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Castelo', '3531605', 1);
insert into regiao (descricao, codigo, nivel) values ('Monte Mor', '3531803', 1);
insert into regiao (descricao, codigo, nivel) values ('Monteiro Lobato', '3531704', 1);
insert into regiao (descricao, codigo, nivel) values ('Morro Agudo', '3531902', 1);
insert into regiao (descricao, codigo, nivel) values ('Morungaba', '3532009', 1);
insert into regiao (descricao, codigo, nivel) values ('Motuca', '3532058', 1);
insert into regiao (descricao, codigo, nivel) values ('Murutinga do Sul', '3532108', 1);
insert into regiao (descricao, codigo, nivel) values ('Nantes', '3532157', 1);
insert into regiao (descricao, codigo, nivel) values ('Narandiba', '3532207', 1);
insert into regiao (descricao, codigo, nivel) values ('Natividade da Serra', '3532306', 1);
insert into regiao (descricao, codigo, nivel) values ('Nazaré Paulista', '3532405', 1);
insert into regiao (descricao, codigo, nivel) values ('Neves Paulista', '3532504', 1);
insert into regiao (descricao, codigo, nivel) values ('Nhandeara', '3532603', 1);
insert into regiao (descricao, codigo, nivel) values ('Nipoã', '3532702', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Aliança', '3532801', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Campina', '3532827', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Canaã Paulista', '3532843', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Castilho', '3532868', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Europa', '3532900', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Granada', '3533007', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Guataporanga', '3533106', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Independência', '3533205', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Luzitânia', '3533304', 1);
insert into regiao (descricao, codigo, nivel) values ('Nova Odessa', '3533403', 1);
insert into regiao (descricao, codigo, nivel) values ('Novais', '3533254', 1);
insert into regiao (descricao, codigo, nivel) values ('Novo Horizonte', '3533502', 1);
insert into regiao (descricao, codigo, nivel) values ('Nuporanga', '3533601', 1);
insert into regiao (descricao, codigo, nivel) values ('Ocauçu', '3533700', 1);
insert into regiao (descricao, codigo, nivel) values ('Óleo', '3533809', 1);
insert into regiao (descricao, codigo, nivel) values ('Olímpia', '3533908', 1);
insert into regiao (descricao, codigo, nivel) values ('Onda Verde', '3534005', 1);
insert into regiao (descricao, codigo, nivel) values ('Oriente', '3534104', 1);
insert into regiao (descricao, codigo, nivel) values ('Orindiúva', '3534203', 1);
insert into regiao (descricao, codigo, nivel) values ('Orlândia', '3534302', 1);
insert into regiao (descricao, codigo, nivel) values ('Osasco', '3534401', 1);
insert into regiao (descricao, codigo, nivel) values ('Oscar Bressane', '3534500', 1);
insert into regiao (descricao, codigo, nivel) values ('Osvaldo Cruz', '3534609', 1);
insert into regiao (descricao, codigo, nivel) values ('Ourinhos', '3534708', 1);
insert into regiao (descricao, codigo, nivel) values ('Ouro Verde', '3534807', 1);
insert into regiao (descricao, codigo, nivel) values ('Ouroeste', '3534757', 1);
insert into regiao (descricao, codigo, nivel) values ('Pacaembu', '3534906', 1);
insert into regiao (descricao, codigo, nivel) values ('Palestina', '3535002', 1);
insert into regiao (descricao, codigo, nivel) values ('Palmares Paulista', '3535101', 1);
insert into regiao (descricao, codigo, nivel) values (E'Palmeira d''Oeste', '3535200', 1);
insert into regiao (descricao, codigo, nivel) values ('Palmital', '3535309', 1);
insert into regiao (descricao, codigo, nivel) values ('Panorama', '3535408', 1);
insert into regiao (descricao, codigo, nivel) values ('Paraguaçu Paulista', '3535507', 1);
insert into regiao (descricao, codigo, nivel) values ('Paraibuna', '3535606', 1);
insert into regiao (descricao, codigo, nivel) values ('Paraíso', '3535705', 1);
insert into regiao (descricao, codigo, nivel) values ('Paranapanema', '3535804', 1);
insert into regiao (descricao, codigo, nivel) values ('Paranapuã', '3535903', 1);
insert into regiao (descricao, codigo, nivel) values ('Parapuã', '3536000', 1);
insert into regiao (descricao, codigo, nivel) values ('Pardinho', '3536109', 1);
insert into regiao (descricao, codigo, nivel) values ('Pariquera-Açu', '3536208', 1);
insert into regiao (descricao, codigo, nivel) values ('Parisi', '3536257', 1);
insert into regiao (descricao, codigo, nivel) values ('Patrocínio Paulista', '3536307', 1);
insert into regiao (descricao, codigo, nivel) values ('Paulicéia', '3536406', 1);
insert into regiao (descricao, codigo, nivel) values ('Paulínia', '3536505', 1);
insert into regiao (descricao, codigo, nivel) values ('Paulistânia', '3536570', 1);
insert into regiao (descricao, codigo, nivel) values ('Paulo de Faria', '3536604', 1);
insert into regiao (descricao, codigo, nivel) values ('Pederneiras', '3536703', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedra Bela', '3536802', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedranópolis', '3536901', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedregulho', '3537008', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedreira', '3537107', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedrinhas Paulista', '3537156', 1);
insert into regiao (descricao, codigo, nivel) values ('Pedro de Toledo', '3537206', 1);
insert into regiao (descricao, codigo, nivel) values ('Penápolis', '3537305', 1);
insert into regiao (descricao, codigo, nivel) values ('Pereira Barreto', '3537404', 1);
insert into regiao (descricao, codigo, nivel) values ('Pereiras', '3537503', 1);
insert into regiao (descricao, codigo, nivel) values ('Peruíbe', '3537602', 1);
insert into regiao (descricao, codigo, nivel) values ('Piacatu', '3537701', 1);
insert into regiao (descricao, codigo, nivel) values ('Piedade', '3537800', 1);
insert into regiao (descricao, codigo, nivel) values ('Pilar do Sul', '3537909', 1);
insert into regiao (descricao, codigo, nivel) values ('Pindamonhangaba', '3538006', 1);
insert into regiao (descricao, codigo, nivel) values ('Pindorama', '3538105', 1);
insert into regiao (descricao, codigo, nivel) values ('Pinhalzinho', '3538204', 1);
insert into regiao (descricao, codigo, nivel) values ('Piquerobi', '3538303', 1);
insert into regiao (descricao, codigo, nivel) values ('Piquete', '3538501', 1);
insert into regiao (descricao, codigo, nivel) values ('Piracaia', '3538600', 1);
insert into regiao (descricao, codigo, nivel) values ('Piracicaba', '3538709', 1);
insert into regiao (descricao, codigo, nivel) values ('Piraju', '3538808', 1);
insert into regiao (descricao, codigo, nivel) values ('Pirajuí', '3538907', 1);
insert into regiao (descricao, codigo, nivel) values ('Pirangi', '3539004', 1);
insert into regiao (descricao, codigo, nivel) values ('Pirapora do Bom Jesus', '3539103', 1);
insert into regiao (descricao, codigo, nivel) values ('Pirapozinho', '3539202', 1);
insert into regiao (descricao, codigo, nivel) values ('Pirassununga', '3539301', 1);
insert into regiao (descricao, codigo, nivel) values ('Piratininga', '3539400', 1);
insert into regiao (descricao, codigo, nivel) values ('Pitangueiras', '3539509', 1);
insert into regiao (descricao, codigo, nivel) values ('Planalto', '3539608', 1);
insert into regiao (descricao, codigo, nivel) values ('Platina', '3539707', 1);
insert into regiao (descricao, codigo, nivel) values ('Poá', '3539806', 1);
insert into regiao (descricao, codigo, nivel) values ('Poloni', '3539905', 1);
insert into regiao (descricao, codigo, nivel) values ('Pompeia', '3540002', 1);
insert into regiao (descricao, codigo, nivel) values ('Pongaí', '3540101', 1);
insert into regiao (descricao, codigo, nivel) values ('Pontal', '3540200', 1);
insert into regiao (descricao, codigo, nivel) values ('Pontalinda', '3540259', 1);
insert into regiao (descricao, codigo, nivel) values ('Pontes Gestal', '3540309', 1);
insert into regiao (descricao, codigo, nivel) values ('Populina', '3540408', 1);
insert into regiao (descricao, codigo, nivel) values ('Porangaba', '3540507', 1);
insert into regiao (descricao, codigo, nivel) values ('Porto Feliz', '3540606', 1);
insert into regiao (descricao, codigo, nivel) values ('Porto Ferreira', '3540705', 1);
insert into regiao (descricao, codigo, nivel) values ('Potim', '3540754', 1);
insert into regiao (descricao, codigo, nivel) values ('Potirendaba', '3540804', 1);
insert into regiao (descricao, codigo, nivel) values ('Pracinha', '3540853', 1);
insert into regiao (descricao, codigo, nivel) values ('Pradópolis', '3540903', 1);
insert into regiao (descricao, codigo, nivel) values ('Praia Grande', '3541000', 1);
insert into regiao (descricao, codigo, nivel) values ('Pratânia', '3541059', 1);
insert into regiao (descricao, codigo, nivel) values ('Presidente Alves', '3541109', 1);
insert into regiao (descricao, codigo, nivel) values ('Presidente Bernardes', '3541208', 1);
insert into regiao (descricao, codigo, nivel) values ('Presidente Epitácio', '3541307', 1);
insert into regiao (descricao, codigo, nivel) values ('Presidente Prudente', '3541406', 1);
insert into regiao (descricao, codigo, nivel) values ('Presidente Venceslau', '3541505', 1);
insert into regiao (descricao, codigo, nivel) values ('Promissão', '3541604', 1);
insert into regiao (descricao, codigo, nivel) values ('Quadra', '3541653', 1);
insert into regiao (descricao, codigo, nivel) values ('Quatá', '3541703', 1);
insert into regiao (descricao, codigo, nivel) values ('Queiroz', '3541802', 1);
insert into regiao (descricao, codigo, nivel) values ('Queluz', '3541901', 1);
insert into regiao (descricao, codigo, nivel) values ('Quintana', '3542008', 1);
insert into regiao (descricao, codigo, nivel) values ('Rafard', '3542107', 1);
insert into regiao (descricao, codigo, nivel) values ('Rancharia', '3542206', 1);
insert into regiao (descricao, codigo, nivel) values ('Redenção da Serra', '3542305', 1);
insert into regiao (descricao, codigo, nivel) values ('Regente Feijó', '3542404', 1);
insert into regiao (descricao, codigo, nivel) values ('Reginópolis', '3542503', 1);
insert into regiao (descricao, codigo, nivel) values ('Registro', '3542602', 1);
insert into regiao (descricao, codigo, nivel) values ('Restinga', '3542701', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeira', '3542800', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Bonito', '3542909', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Branco', '3543006', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Corrente', '3543105', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão do Sul', '3543204', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão dos Índios', '3543238', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Grande', '3543253', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Pires', '3543303', 1);
insert into regiao (descricao, codigo, nivel) values ('Ribeirão Preto', '3543402', 1);
insert into regiao (descricao, codigo, nivel) values ('Rifaina', '3543600', 1);
insert into regiao (descricao, codigo, nivel) values ('Rincão', '3543709', 1);
insert into regiao (descricao, codigo, nivel) values ('Rinópolis', '3543808', 1);
insert into regiao (descricao, codigo, nivel) values ('Rio Claro', '3543907', 1);
insert into regiao (descricao, codigo, nivel) values ('Rio das Pedras', '3544004', 1);
insert into regiao (descricao, codigo, nivel) values ('Rio Grande da Serra', '3544103', 1);
insert into regiao (descricao, codigo, nivel) values ('Riolândia', '3544202', 1);
insert into regiao (descricao, codigo, nivel) values ('Riversul', '3543501', 1);
insert into regiao (descricao, codigo, nivel) values ('Rosana', '3544251', 1);
insert into regiao (descricao, codigo, nivel) values ('Roseira', '3544301', 1);
insert into regiao (descricao, codigo, nivel) values ('Rubiácea', '3544400', 1);
insert into regiao (descricao, codigo, nivel) values ('Rubineia', '3544509', 1);
insert into regiao (descricao, codigo, nivel) values ('Sabino', '3544608', 1);
insert into regiao (descricao, codigo, nivel) values ('Sagres', '3544707', 1);
insert into regiao (descricao, codigo, nivel) values ('Sales', '3544806', 1);
insert into regiao (descricao, codigo, nivel) values ('Sales Oliveira', '3544905', 1);
insert into regiao (descricao, codigo, nivel) values ('Salesópolis', '3545001', 1);
insert into regiao (descricao, codigo, nivel) values ('Salmourão', '3545100', 1);
insert into regiao (descricao, codigo, nivel) values ('Saltinho', '3545159', 1);
insert into regiao (descricao, codigo, nivel) values ('Salto', '3545209', 1);
insert into regiao (descricao, codigo, nivel) values ('Salto de Pirapora', '3545308', 1);
insert into regiao (descricao, codigo, nivel) values ('Salto Grande', '3545407', 1);
insert into regiao (descricao, codigo, nivel) values ('Sandovalina', '3545506', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Adélia', '3545605', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Albertina', '3545704', 1);
insert into regiao (descricao, codigo, nivel) values (E'Santa Bárbara d''Oeste', '3545803', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Branca', '3546009', 1);
insert into regiao (descricao, codigo, nivel) values (E'Santa Clara d''Oeste', '3546108', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Cruz da Conceição', '3546207', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Cruz da Esperança', '3546256', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Cruz das Palmeiras', '3546306', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Cruz do Rio Pardo', '3546405', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Ernestina', '3546504', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Fé do Sul', '3546603', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Gertrudes', '3546702', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Isabel', '3546801', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Lúcia', '3546900', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Maria da Serra', '3547007', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Mercedes', '3547106', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Rita do Passa Quatro', '3547502', 1);
insert into regiao (descricao, codigo, nivel) values (E'Santa Rita d''Oeste', '3547403', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Rosa de Viterbo', '3547601', 1);
insert into regiao (descricao, codigo, nivel) values ('Santa Salete', '3547650', 1);
insert into regiao (descricao, codigo, nivel) values ('Santana da Ponte Pensa', '3547205', 1);
insert into regiao (descricao, codigo, nivel) values ('Santana de Parnaíba', '3547304', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Anastácio', '3547700', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo André', '3547809', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Antônio da Alegria', '3547908', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Antônio de Posse', '3548005', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Antônio do Aracanguá', '3548054', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Antônio do Jardim', '3548104', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Antônio do Pinhal', '3548203', 1);
insert into regiao (descricao, codigo, nivel) values ('Santo Expedito', '3548302', 1);
insert into regiao (descricao, codigo, nivel) values ('Santópolis do Aguapeí', '3548401', 1);
insert into regiao (descricao, codigo, nivel) values ('Santos', '3548500', 1);
insert into regiao (descricao, codigo, nivel) values ('São Bento do Sapucaí', '3548609', 1);
insert into regiao (descricao, codigo, nivel) values ('São Bernardo do Campo', '3548708', 1);
insert into regiao (descricao, codigo, nivel) values ('São Caetano do Sul', '3548807', 1);
insert into regiao (descricao, codigo, nivel) values ('São Carlos', '3548906', 1);
insert into regiao (descricao, codigo, nivel) values ('São Francisco', '3549003', 1);
insert into regiao (descricao, codigo, nivel) values ('São João da Boa Vista', '3549102', 1);
insert into regiao (descricao, codigo, nivel) values ('São João das Duas Pontes', '3549201', 1);
insert into regiao (descricao, codigo, nivel) values ('São João de Iracema', '3549250', 1);
insert into regiao (descricao, codigo, nivel) values (E'São João do Pau-d''Alho', '3549300', 1);
insert into regiao (descricao, codigo, nivel) values ('São Joaquim da Barra', '3549409', 1);
insert into regiao (descricao, codigo, nivel) values ('São José da Bela Vista', '3549508', 1);
insert into regiao (descricao, codigo, nivel) values ('São José do Barreiro', '3549607', 1);
insert into regiao (descricao, codigo, nivel) values ('São José do Rio Pardo', '3549706', 1);
insert into regiao (descricao, codigo, nivel) values ('São José do Rio Preto', '3549805', 1);
insert into regiao (descricao, codigo, nivel) values ('São José dos Campos', '3549904', 1);
insert into regiao (descricao, codigo, nivel) values ('São Lourenço da Serra', '3549953', 1);
insert into regiao (descricao, codigo, nivel) values ('São Luiz do Paraitinga', '3550001', 1);
insert into regiao (descricao, codigo, nivel) values ('São Manuel', '3550100', 1);
insert into regiao (descricao, codigo, nivel) values ('São Miguel Arcanjo', '3550209', 1);
insert into regiao (descricao, codigo, nivel) values ('São Pedro', '3550407', 1);
insert into regiao (descricao, codigo, nivel) values ('São Pedro do Turvo', '3550506', 1);
insert into regiao (descricao, codigo, nivel) values ('São Roque', '3550605', 1);
insert into regiao (descricao, codigo, nivel) values ('São Sebastião', '3550704', 1);
insert into regiao (descricao, codigo, nivel) values ('São Sebastião da Grama', '3550803', 1);
insert into regiao (descricao, codigo, nivel) values ('São Simão', '3550902', 1);
insert into regiao (descricao, codigo, nivel) values ('São Vicente', '3551009', 1);
insert into regiao (descricao, codigo, nivel) values ('Sarapuí', '3551108', 1);
insert into regiao (descricao, codigo, nivel) values ('Sarutaiá', '3551207', 1);
insert into regiao (descricao, codigo, nivel) values ('Sebastianópolis do Sul', '3551306', 1);
insert into regiao (descricao, codigo, nivel) values ('Serra Azul', '3551405', 1);
insert into regiao (descricao, codigo, nivel) values ('Serra Negra', '3551603', 1);
insert into regiao (descricao, codigo, nivel) values ('Serrana', '3551504', 1);
insert into regiao (descricao, codigo, nivel) values ('Sertãozinho', '3551702', 1);
insert into regiao (descricao, codigo, nivel) values ('Sete Barras', '3551801', 1);
insert into regiao (descricao, codigo, nivel) values ('Severínia', '3551900', 1);
insert into regiao (descricao, codigo, nivel) values ('Silveiras', '3552007', 1);
insert into regiao (descricao, codigo, nivel) values ('Socorro', '3552106', 1);
insert into regiao (descricao, codigo, nivel) values ('Sorocaba', '3552205', 1);
insert into regiao (descricao, codigo, nivel) values ('Sud Mennucci', '3552304', 1);
insert into regiao (descricao, codigo, nivel) values ('Sumaré', '3552403', 1);
insert into regiao (descricao, codigo, nivel) values ('Suzanápolis', '3552551', 1);
insert into regiao (descricao, codigo, nivel) values ('Suzano', '3552502', 1);
insert into regiao (descricao, codigo, nivel) values ('Tabapuã', '3552601', 1);
insert into regiao (descricao, codigo, nivel) values ('Tabatinga', '3552700', 1);
insert into regiao (descricao, codigo, nivel) values ('Taboão da Serra', '3552809', 1);
insert into regiao (descricao, codigo, nivel) values ('Taciba', '3552908', 1);
insert into regiao (descricao, codigo, nivel) values ('Taguaí', '3553005', 1);
insert into regiao (descricao, codigo, nivel) values ('Taiaçu', '3553104', 1);
insert into regiao (descricao, codigo, nivel) values ('Taiúva', '3553203', 1);
insert into regiao (descricao, codigo, nivel) values ('Tambaú', '3553302', 1);
insert into regiao (descricao, codigo, nivel) values ('Tanabi', '3553401', 1);
insert into regiao (descricao, codigo, nivel) values ('Tapiraí', '3553500', 1);
insert into regiao (descricao, codigo, nivel) values ('Tapiratiba', '3553609', 1);
insert into regiao (descricao, codigo, nivel) values ('Taquaral', '3553658', 1);
insert into regiao (descricao, codigo, nivel) values ('Taquaritinga', '3553708', 1);
insert into regiao (descricao, codigo, nivel) values ('Taquarituba', '3553807', 1);
insert into regiao (descricao, codigo, nivel) values ('Taquarivaí', '3553856', 1);
insert into regiao (descricao, codigo, nivel) values ('Tarabai', '3553906', 1);
insert into regiao (descricao, codigo, nivel) values ('Tarumã', '3553955', 1);
insert into regiao (descricao, codigo, nivel) values ('Tatuí', '3554003', 1);
insert into regiao (descricao, codigo, nivel) values ('Taubaté', '3554102', 1);
insert into regiao (descricao, codigo, nivel) values ('Tejupá', '3554201', 1);
insert into regiao (descricao, codigo, nivel) values ('Teodoro Sampaio', '3554300', 1);
insert into regiao (descricao, codigo, nivel) values ('Terra Roxa', '3554409', 1);
insert into regiao (descricao, codigo, nivel) values ('Tietê', '3554508', 1);
insert into regiao (descricao, codigo, nivel) values ('Timburi', '3554607', 1);
insert into regiao (descricao, codigo, nivel) values ('Torre de Pedra', '3554656', 1);
insert into regiao (descricao, codigo, nivel) values ('Torrinha', '3554706', 1);
insert into regiao (descricao, codigo, nivel) values ('Trabiju', '3554755', 1);
insert into regiao (descricao, codigo, nivel) values ('Tremembé', '3554805', 1);
insert into regiao (descricao, codigo, nivel) values ('Três Fronteiras', '3554904', 1);
insert into regiao (descricao, codigo, nivel) values ('Tuiuti', '3554953', 1);
insert into regiao (descricao, codigo, nivel) values ('Tupã', '3555000', 1);
insert into regiao (descricao, codigo, nivel) values ('Tupi Paulista', '3555109', 1);
insert into regiao (descricao, codigo, nivel) values ('Turiúba', '3555208', 1);
insert into regiao (descricao, codigo, nivel) values ('Turmalina', '3555307', 1);
insert into regiao (descricao, codigo, nivel) values ('Ubarana', '3555356', 1);
insert into regiao (descricao, codigo, nivel) values ('Ubatuba', '3555406', 1);
insert into regiao (descricao, codigo, nivel) values ('Ubirajara', '3555505', 1);
insert into regiao (descricao, codigo, nivel) values ('Uchoa', '3555604', 1);
insert into regiao (descricao, codigo, nivel) values ('União Paulista', '3555703', 1);
insert into regiao (descricao, codigo, nivel) values ('Urânia', '3555802', 1);
insert into regiao (descricao, codigo, nivel) values ('Uru', '3555901', 1);
insert into regiao (descricao, codigo, nivel) values ('Urupês', '3556008', 1);
insert into regiao (descricao, codigo, nivel) values ('Valentim Gentil', '3556107', 1);
insert into regiao (descricao, codigo, nivel) values ('Valinhos', '3556206', 1);
insert into regiao (descricao, codigo, nivel) values ('Valparaíso', '3556305', 1);
insert into regiao (descricao, codigo, nivel) values ('Vargem', '3556354', 1);
insert into regiao (descricao, codigo, nivel) values ('Vargem Grande do Sul', '3556404', 1);
insert into regiao (descricao, codigo, nivel) values ('Vargem Grande Paulista', '3556453', 1);
insert into regiao (descricao, codigo, nivel) values ('Várzea Paulista', '3556503', 1);
insert into regiao (descricao, codigo, nivel) values ('Vera Cruz', '3556602', 1);
insert into regiao (descricao, codigo, nivel) values ('Vinhedo', '3556701', 1);
insert into regiao (descricao, codigo, nivel) values ('Viradouro', '3556800', 1);
insert into regiao (descricao, codigo, nivel) values ('Vista Alegre do Alto', '3556909', 1);
insert into regiao (descricao, codigo, nivel) values ('Vitória Brasil', '3556958', 1);
insert into regiao (descricao, codigo, nivel) values ('Votorantim', '3557006', 1);
insert into regiao (descricao, codigo, nivel) values ('Votuporanga', '3557105', 1);
insert into regiao (descricao, codigo, nivel) values ('Zacarias', '3557154', 1);
